<map id="PyG4ExceptionHandler::Notify" name="PyG4ExceptionHandler::Notify">
<area shape="rect" id="node2" href="$d8/d3c/ts__scorers_8cc.html#ad81d1cdebbda7d39795160acd3aebd24" title="message" alt="" coords="231,81,313,109"/>
<area shape="rect" id="node3" href="$d7/d23/namespaceG4Threading.html#a457962a93ab41c7f9575dde6cbe9b78c" title="G4Threading::G4GetNumber\lOfCores" alt="" coords="361,5,577,49"/>
<area shape="rect" id="node4" href="$d4/daa/classG4RunManager.html#a3a19f2283ba22cbee8ba640d160d2e7e" title="G4RunManager::GetVerbose\lLevel" alt="" coords="363,73,575,117"/>
<area shape="rect" id="node5" href="$d4/daa/classG4RunManager.html#a9e042965b0d460b1d492ab48de141b2a" title="G4RunManager::SetVerbose\lLevel" alt="" coords="364,141,575,185"/>
<area shape="rect" id="node6" href="$de/d51/classG4RunManagerKernel.html#aea8a72d21f60b3e6436eed9b651dc247" title="G4RunManagerKernel\l::SetVerboseLevel" alt="" coords="625,141,793,185"/>
</map>
